# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: weather.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rweather.proto\x12\x08\x62\x65.cloud\"\"\n\x0eWeatherRequest\x12\x10\n\x08location\x18\x01 \x01(\t\":\n\x0fWeatherResponse\x12\x13\n\x0btemperature\x18\x01 \x01(\t\x12\x12\n\nconditions\x18\x02 \x01(\t2W\n\x0eWeatherService\x12\x45\n\x0eGetWeatherInfo\x12\x18.be.cloud.WeatherRequest\x1a\x19.be.cloud.WeatherResponseB\x02P\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'weather_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'P\001'
  _globals['_WEATHERREQUEST']._serialized_start=27
  _globals['_WEATHERREQUEST']._serialized_end=61
  _globals['_WEATHERRESPONSE']._serialized_start=63
  _globals['_WEATHERRESPONSE']._serialized_end=121
  _globals['_WEATHERSERVICE']._serialized_start=123
  _globals['_WEATHERSERVICE']._serialized_end=210
# @@protoc_insertion_point(module_scope)
