// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: weather.proto

// Protobuf Java Version: 3.25.1
package be.cloud;

public interface WeatherResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:be.cloud.WeatherResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string temperature = 1;</code>
   * @return The temperature.
   */
  java.lang.String getTemperature();
  /**
   * <code>string temperature = 1;</code>
   * @return The bytes for temperature.
   */
  com.google.protobuf.ByteString
      getTemperatureBytes();

  /**
   * <code>string conditions = 2;</code>
   * @return The conditions.
   */
  java.lang.String getConditions();
  /**
   * <code>string conditions = 2;</code>
   * @return The bytes for conditions.
   */
  com.google.protobuf.ByteString
      getConditionsBytes();
}
