// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: weather.proto

// Protobuf Java Version: 3.25.1
package be.cloud;

public final class Weather {
  private Weather() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_be_cloud_WeatherRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_be_cloud_WeatherRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_be_cloud_WeatherResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_be_cloud_WeatherResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rweather.proto\022\010be.cloud\"\"\n\016WeatherRequ" +
      "est\022\020\n\010location\030\001 \001(\t\":\n\017WeatherResponse" +
      "\022\023\n\013temperature\030\001 \001(\t\022\022\n\nconditions\030\002 \001(" +
      "\t2W\n\016WeatherService\022E\n\016GetWeatherInfo\022\030." +
      "be.cloud.WeatherRequest\032\031.be.cloud.Weath" +
      "erResponseB\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_be_cloud_WeatherRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_be_cloud_WeatherRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_be_cloud_WeatherRequest_descriptor,
        new java.lang.String[] { "Location", });
    internal_static_be_cloud_WeatherResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_be_cloud_WeatherResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_be_cloud_WeatherResponse_descriptor,
        new java.lang.String[] { "Temperature", "Conditions", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
